version: "3.5"

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    command: ["postgres", "-c", "log_statement=all"]